version: '3.8'
services:
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:123456789@db/postgres
      - SECRET_KEY=your_secret_key
      - BASE_URL=http://localhost:5000/
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - db
    # Override the default CMD from the Dockerfile
    # Use wait-for-it.sh to check for db readiness, then start the Flask app
    command: ["/wait-for-it.sh", "db:5432", "--timeout=30", "--", "python", "-m", "main"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
